// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxs47YTSuwm0cRtre3uRwf4yd3fd-KbJo',
    appId: '1:802489692934:web:55b6b3b4bb371efa61e487',
    messagingSenderId: '802489692934',
    projectId: 'socialsphere-9a833',
    authDomain: 'socialsphere-9a833.firebaseapp.com',
    storageBucket: 'socialsphere-9a833.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGOa4BVOwD-TpMdA5OgNcaaTYyFaHKDFI',
    appId: '1:802489692934:android:38873daa353d8d0961e487',
    messagingSenderId: '802489692934',
    projectId: 'socialsphere-9a833',
    storageBucket: 'socialsphere-9a833.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAizu124ikIMMx7dexRujlyATXrPDTosE',
    appId: '1:802489692934:ios:876526bd8fac767961e487',
    messagingSenderId: '802489692934',
    projectId: 'socialsphere-9a833',
    storageBucket: 'socialsphere-9a833.firebasestorage.app',
    iosBundleId: 'com.example.socialSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAizu124ikIMMx7dexRujlyATXrPDTosE',
    appId: '1:802489692934:ios:876526bd8fac767961e487',
    messagingSenderId: '802489692934',
    projectId: 'socialsphere-9a833',
    storageBucket: 'socialsphere-9a833.firebasestorage.app',
    iosBundleId: 'com.example.socialSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxs47YTSuwm0cRtre3uRwf4yd3fd-KbJo',
    appId: '1:802489692934:web:1b106258399e35f661e487',
    messagingSenderId: '802489692934',
    projectId: 'socialsphere-9a833',
    authDomain: 'socialsphere-9a833.firebaseapp.com',
    storageBucket: 'socialsphere-9a833.firebasestorage.app',
  );
}
